### ISSUE TITLE
Un-needed directory

### ISSUE THREAD

**Issue by JesterOrNot** [RXT0112/Zernit#22]
Why is the target folder checked in when it is added to the .gitignore?

**Comment by Kreyren** [comment]
@JesterOrNot I was experimenting with methods for git to ignore pathname without git ignore, because I don't like it being in the root of the repository.

target was added during experimenting with `.git/info/exclude` which doesn't seem to be stored after the repository is forked or branch checked out with -b flag. (using that for experiments atm)

---

Note that this repository is in (what I call) init phase so all the commits will be remade once I decide on quality assurance, documentation method and automation. Also I'm not satisfied with the way the code is written so that will be refactored too.

**Comment by Kreyren** [comment]
closing as stale unless new response is provided
