### ISSUE TITLE
Nile

### ISSUE THREAD

**Issue by renault24** [RXT0112/Zernit#28]
Add some extra features which is not releated to any package manager. also make an shell if possible. good luck : )

**Comment by Kreyren** [comment]
> Add some extra features which is not releated to any package manager. 

Elaborate? 

Currently i plan on adding system-from-scratch building so that it will be able to make FSH,toolchain,kernel for export or import + method to self-boot for installation.

I also plan on adding modding functionality for games

>  also make an shell if possible. 

It will support shell for downstream in terms of gentoo and exherbo compatibility with possible custom downstream like https://github.com/exheredludis/exheredrey-0 which is my WIP fork of exheres-0 for paludis - For zernit downstream it is not yet decided what will be used but shell is strong candidate where i may support multiple languages for downstream.

Using shell as backend is not possible for cross-platform compatibility without exporting bash on windows or using cygwin and shell would require lots of rewritting for library implementation which would limit zernit on functionality. See winetricks or https://github.com/kreytricks for the issue.

**Comment by Kreyren** [comment]
Closing as stale will reopen if response is provided
